-- Database: ControleClientesProdudos

-- DROP DATABASE IF EXISTS "ControleClientesProdudos";

CREATE DATABASE "ControleClientesProdudos"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
-- Table: public.clientes

-- DROP TABLE IF EXISTS public.clientes;

CREATE TABLE IF NOT EXISTS public.clientes
(
    idcliente integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000 CACHE 1 ),
    nome character varying COLLATE pg_catalog."default",
    endereco character varying COLLATE pg_catalog."default",
    telefone character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    CONSTRAINT clientes_pk PRIMARY KEY (idcliente)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.clientes
    OWNER to postgres;
	
-- Table: public.produtos

-- DROP TABLE IF EXISTS public.produtos;

CREATE TABLE IF NOT EXISTS public.produtos
(
    idproduto integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000 CACHE 1 ),
    nome character varying COLLATE pg_catalog."default",
    descricao character varying COLLATE pg_catalog."default",
    preco double precision,
    estoque integer,
    CONSTRAINT clientes_pk_1 PRIMARY KEY (idproduto)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.produtos
    OWNER to postgres;

COMMENT ON COLUMN public.produtos.idproduto
    IS 'Código do produto';
	
-- Table: public.vendas

-- DROP TABLE IF EXISTS public.vendas;

CREATE TABLE IF NOT EXISTS public.vendas
(
    idvenda integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 10000 CACHE 1 ),
    qtditens integer,
    data date,
    idcliente integer NOT NULL,
    idproduto integer NOT NULL,
    CONSTRAINT vendas_pk PRIMARY KEY (idvenda)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.vendas
    OWNER to postgres;